LetsGoBootstrap/LetsGoBootstrap/Controllers/ContactController.cs
using LetsGoBootstrap.Models;
using LetsGoBootstrap.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LetsGoBootstrap.Controllers
{
    public class ContactController:Controller
    {
        private IContactRepository _contactRepository = null;
        public ContactController(IContactRepository contactRepository)
        {
            _contactRepository = contactRepository;
        }

        public ActionResult Index()
        {
            ViewBag.ContactTabClass = "active";
            ViewBag.Address = "active";
            return View();
        }

        [HttpPost]
        public ActionResult Index(VistorContactUsViewModel aModel)
        {
            ViewBag.ContactTabClass = "active";
            ViewBag.ContactUs = "active";
            if (ModelState.IsValid)
            {
                try
                {
                    var aContact = new Contact() {
                        FirstName=aModel.FirstName,
                        LastName=aModel.LastName,
                        Email=aModel.Email,
                        Message=aModel.Message
                    };
                    _contactRepository.SendMessage()
                }
                catch (Exception)
                {

                    throw;
                }
            }
            return View(aModel);
        }
    }
}

LetsGoBootstrap/LetsGoBootstrap/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LetsGoBootstrap.Controllers
{
    public class ProductController:Controller
    {
        public ProductController()
        {

        }

        public ViewResult Index()
        {
            ViewBag.ProductTabClass = "active";
            return View();

        }
    }
}

LetsGoBootstrap/LetsGoBootstrap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LetsGoBootstrap</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/United-bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/site.css" />
</head>
<body>
    <header>
        <nav id="divMenu" class="navbar navbar-default navbar-static-top" role="navigation">
            <div id="divHeader" class="container">
                <div class="navbar-header">
                    <a href="#" class="navbar-brand"><img src="~/Images/Logo.png" alt="Project-M" class="img-responsive" /></a>
                    <button type="button" data-toggle="collapse" data-target="#divCollapsibleMenu" class="navbar-toggle">
                        <span class="glyphicon glyphicon-menu-down"></span>
                    </button>
                </div>
                <div id="divCollapsibleMenu" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="nav @ViewBag.HomeTabClass"><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav @ViewBag.ProductTabClass"><a asp-controller="Product" asp-action="Index">Products</a></li>
                        <li class="nav @ViewBag.ContactTabClass"><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                    </ul>
                    <form id="frmSearch" class="navbar-form " role="search">
                        <div class="input-group">
                            <div class="form-group">
                                <input id="txtSearch" type="text" class="form-control" placeholder="Search" />
                            </div>
                            <div class="input-group-btn">
                                <button id="btnSearch" type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </nav>
    </header>


    <section id="divBody" class="container">

        <div class="row">

            <div id="divSideBar" class="col-sm-2">
                <div id="divSideBarAdmin"></div>
                <div id="divSideBarNormal">
                    <ul class="nav flex-column">
                        <li class="nav-item @ViewBag.HomeTabClass">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item @ViewBag.ProductTabClass">
                            <a class="nav-link" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item @ViewBag.ContactTabClass">
                            <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact us</a>
                        </li>

                    </ul>
                </div>
            </div>

            <div id="divBodyInner" class="col-sm-10">
                @RenderBody()
            </div>
        </div>
    </section>

    <div id="divFooter" class="container">
        <hr />
        <footer>
            &copy;ProjectM - @DateTime.Now.Year
        </footer>
    </div>
    @*<div id="page">
            <header class="container-fluid">
                <div id="menu" class="navbar navbar-default ">
                    <div id="logo-menuItems" class="col-md-offset-2">
                        <div id="logo"class="navbar-header">
                            <a href="." class="navbar-brand">Site Name</a>
                        </div>
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Home</a>
                                <a href="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Category</a>
                                <a href="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Others</a>
                                <a href="" asp-controller="Home" asp-action="Index" class="btn btn-primary">Contact us</a>
                            </li>
                        </ul>
                    </div>
                    <div id="mainSearch" >
                        <form action="/" method="post" class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                <input type="text"  class="form-control" placeholder="search" />
                                <button id="btnMainSearch" asp-controller="Home" asp-action="Index" class="btn btn-primary">Search</button>
                            </div>
                        </form>
                    </div>
                </div>
            </header>
            <section id="mainBody" class="container">
                <section id="sideBar" class="col-md-2 col-sm-3">

                    A side bar

                </section>
                <section id="mainDisplay" class="col-md-10 col-sm-9">
                    <div class="row visible-md visible-lg" id="bannerRow">
                        <img src="~/Images/mainBanner.jpg" alt="Site name" class="col-md-12" />
                    </div>
                    @RenderBody()

                </section>
            </section>

            <hr id="bottomLine" />
            <footer id="footer" class="container">
                I am a footer
            </footer>

        </div>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</body>
</html>